### ISSUE TITLE
methods section

### ISSUE THREAD

**Issue by alecgt** [alecgt/prelim#2]
Ready for you to read, @vnminin

**Comment by vnminin** [comment]
Please "git rm" .bbl file and "git add" your .bib file, @alecgt. I've accidentally ran bibtex on your source and ruined your refs. In general, it is better to have .bib file under version control. Thanks.

**Comment by alecgt** [comment]
sorry about that @vnminin . bbl file is removed for AGT_prelim_report, and the bib file has been pushed
